/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.truongvm;

import org.junit.jupiter.api.Test;

import com.arrayandhash.ArrayAndHashSolution;

import static org.junit.jupiter.api.Assertions.*;

class ArrayAndHashTest {
    ArrayAndHashSolution test = new ArrayAndHashSolution();

    // 217
    @Test
    void containDuplicateTest() {
        // assertEquals(test.containsDuplicate(new int[] {}), false);
        assertEquals(test.containsDuplicate(new int[] { 1, 1 }), true, "Test 1 failed");
        assertEquals(test.containsDuplicate(new int[] { 1, 5, 6, 2, 3, 4, 2, 3, 1, 2,
                4 }), true, "Test 2 failed");
        assertEquals(test.containsDuplicate(new int[] { 1, 2, 4, 5, 7, 8, 111, 112
        }), false, "Test 3 failed");
        assertEquals(test.containsDuplicate(new int[] { 11, 2, 4, 5, 7, 8, 111, 112,
                113, 113 }), true, "Test 4 failed");

    }
}
